In [1]:
"""Q4. For a dataset with the following categorical variables: Color 
(red, green, blue), Size (small, medium, large), and Material (wood, 
metal, plastic), perform label encoding using Python's scikit-learn library. 
Show your code and explain the output."""

from sklearn.preprocessing import LabelEncoder
import pandas as pd

# Sample data
data = {
    'Color': ['red', 'green', 'blue', 'green', 'red'],
    'Size': ['medium', 'small', 'large', 'medium', 'small'],
    'Material': ['wood', 'metal', 'plastic', 'metal', 'plastic']
}

# Create a DataFrame
df = pd.DataFrame(data)

# Initialize LabelEncoder
label_encoder = LabelEncoder()

# Apply LabelEncoder to each categorical column
df['Color_encoded'] = label_encoder.fit_transform(df['Color'])
df['Size_encoded'] = label_encoder.fit_transform(df['Size'])
df['Material_encoded'] = label_encoder.fit_transform(df['Material'])

# Drop the original categorical columns
df.drop(['Color', 'Size', 'Material'], axis=1, inplace=True)

# Now, 'Color_encoded', 'Size_encoded', and 'Material_encoded' columns contain the encoded data
print(df)


   Color_encoded  Size_encoded  Material_encoded
0              2             1                 2
1              1             2                 0
2              0             0                 1
3              1             1                 0
4              2             2                 1


In [2]:
"""Q5. Calculate the covariance matrix for the following variables in a 
dataset: Age, Income, and Education level. Interpret the results.
"""

import numpy as np

# Create a dataset or provide values for Age, Income, and Education Level
age = [30, 40, 25, 35, 28]
income = [50000, 60000, 45000, 55000, 48000]
education_level = [12, 16, 14, 18, 15]

# Create a data matrix
data_matrix = np.array([age, income, education_level])

# Calculate the covariance matrix
covariance_matrix = np.cov(data_matrix)

# Print the covariance matrix
print(covariance_matrix)


[[3.53e+01 3.53e+04 7.50e+00]
 [3.53e+04 3.53e+07 7.50e+03]
 [7.50e+00 7.50e+03 5.00e+00]]
